<?php

namespace BookBundle\Repository;

/**
 * CampusManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampusManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
