<?php

namespace BookBundle\Repository;

/**
 * HomeWilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeWilderRepository extends \Doctrine\ORM\EntityRepository
{
}
