<?php

namespace BookBundle\Repository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class languageRepository extends \Doctrine\ORM\EntityRepository
{
}
