<?php

namespace BookBundle\Repository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{

//    public function searchBy($languages)
//    {
//        $qb = $this->createQueryBuilder('l')
//            ->join('l.wilder','w')
//            ->addSelect('w')
//            ->where('l.language = :language')
//            ->setParameter('language', $languages);
//        return $qb->getQuery()->getResult();
//    }
}
