<?php

namespace BookBundle\Repository;

/**
 * ProjectWilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectWilderRepository extends \Doctrine\ORM\EntityRepository
{
}
