<?php

namespace BookBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBy($schools = null, $categories = null, $promotion = null)
    {
        $qb = $this->createQueryBuilder('p');

        if ($schools) {
            $qb
                ->andWhere('p.school IN (:school)')
                ->setParameter('school', $schools);
        }
        if ($categories) {
            $qb
                ->andWhere('p.category IN (:category)')
                ->setParameter('category', $categories);
        }
        return $qb->getQuery()->getResult();
    }

    public function getLike($input)
    {
        $input = "%" . $input . "%";
        $qb = $this->createQueryBuilder('p')
            ->select('p.title','p.id')
            ->where('p.title LIKE :title')
                ->setParameter('title', $input)
            ->getQuery();
        return $qb->getResult();
    }
}
