<?php

namespace BookBundle\Repository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class schoolRepository extends \Doctrine\ORM\EntityRepository
{
}
