<?php

namespace BookBundle\Repository;

/**
 * TechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class technologyRepository extends \Doctrine\ORM\EntityRepository
{
}
