<?php

namespace BookBundle\Repository;

/**
 * WilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wilderRepository extends \Doctrine\ORM\EntityRepository
{
}
